name: flutter_weather_map_new
description: A Flutter application that displays a map and weather information.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^1.3.7
  http: ^1.1.0
  geolocator: ^14.0.0
  cupertino_icons: ^1.0.5
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/capgemini_logo.png